wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/train.py
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669380960.755935
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      - 75
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.13
      5: 0.13.5
      8:
      - 4
      - 5
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: false
env_id:
  desc: null
  value: gyms/TextWorld-v0
exp_name:
  desc: null
  value: train
net:
  desc: null
  value: model_save/TextWorld-avgscore_9.dat
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: text_simplification
